version: "3.9"
name: user-service
services:
  employee_db:
    image: postgres:17-alpine
    container_name: employee-db
    ports:
      - "54321:5432"
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      - POSTGRES_USER=employees
      - POSTGRES_PASSWORD=employees
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - internal
 
  employee_service:
    container_name: employee-service
    build:
      context: .
    env_file: .env
    ports:
      - "8000:8000"
    networks:
      - internal

networks: 
  internal: {}
